### ISSUE TITLE
Nome dos testes

### ISSUE THREAD

**Issue by arthurs159** [Ualace36/BancoDigital-ctd-JAVA#1]
Oi Ualace, olhando seus testes, gostaria de sugerir novos nomes para eles, uma maneira legal de nomear seria fazer assim:

`nome do metodo`__`o que o teste deveria fazer`

Por exemplo:

`transferencia__deveria_transferir_o_dinheiro_de_uma_conta_para_outra`
Além de ser uma boa prática, fica bem mais fácil saber o que cada teste faz.

**Comment by Ualace36** [comment]
Excelente Arthu, fiz os ajustes aqui, obrigado pela análise. Agora comecei a entender melhor, faz todo sentindo deixar mais intuitivo os nomes dos teste. Já fiz os reparos
