### ISSUE TITLE
Fazer novos cenarios de testes

### ISSUE THREAD

**Issue by arthurs159** [Ualace36/BancoDigital-ctd-JAVA#2]
Vejo nos seus testes, que você testa poucos cenários, nos seus métodos, seria legal você testar o cenário quando da certo e quando da errado, por exemplo passando nulo em alguns campos, ou numero negativo em um saque, coisas assim para realmente testar se seus métodos estão funcionando.

Eai, o que acha?

**Comment by Ualace36** [comment]
Arthur, nem tinha vislumbrado essas opções e faz todo o sentido testar essas possibilidades. Confesso que tenho ainda deficiências em testes, mas após suas sugestões conseguir avançar mais nesse ponto. Nessa issue também ja foram feitos os raparos sugeridos.
